### ISSUE TITLE
ComputerCraft doesn't install

### ISSUE THREAD

**Issue by Valiec** [Comprehensive-Minecraft-Archive-Network/CMAN-Archive#6]
Trying to install ComputerCraft produced this error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "/CMAN-Python/CMAN_gui.py", line 54, in instmods
    CMAN_install.install_mod(tkinst.mods[int(_mod)]["Name"])
  File "/CMAN-Python/CMAN_install.py", line 152, in install_mod
    response = requests.get(url)
  (-removed portion of traceback internal to requests-)
requests.exceptions.MissingSchema: Invalid URL 'minecraft.curseforge.com/projects/computercraft/files/2291384/download': No schema supplied. Perhaps you meant http://minecraft.curseforge.com/projects/computercraft/files/2291384/download?

I guess it hasn't been added to the archive correctly?

**Comment by Valiec** [comment]
I have confirmed that this is now fixed. Closing.
